Repository Azure/azure-storage-azcopy, pull requests merged in 2019-11, with the labels that each got.

#723 Allow cancellation during enumeration
  ste/init.go
  ste/mgr-JobMgr.go
Labels: pr-ready-to-merge

#727 After auth error, cancel cleanly instead of immediately exiting
  ste/mgr-JobPartTransferMgr.go
Labels: needs-second-review

#730 Fix credential override for S2S
  cmd/copy.go
  cmd/credentialUtil.go
  testSuite/scripts/test_service_to_service_copy.py
Labels: partner integration
