Repository Azure/azure-storage-azcopy, pull requests merged in 2020-07, with the labels that each got.

#1049 Port ATOMiCNebula's work from the blob SDK to azbfs WRT SAS token time precision
  azbfs/parsing_urls.go
  azbfs/zc_sas_query_params.go
  azbfs/zt_url_file_test.go
Labels: needs-second-review

#1045 Added parallel blob enumeration
  cmd/benchmark.go
  cmd/zc_traverser_benchmark.go
  cmd/zc_traverser_blob.go
  cmd/zt_remove_blob_test.go
  tool_test_perf.sh
Labels: needs-second-review

#1064 Clarify credential validation message
  cmd/credentialUtil.go
  cmd/zt_credentialUtil_test.go
Labels: pr-needs-update

#859 Enable recovering from a random unexpectedEOF error.
  azbfs/url_file.go
  azbfs/zc_policy_retry.go
  azbfs/zc_retry_reader.go
  azbfs/zt_hiddenfuncs_test.go
  azbfs/zt_retry_reader_test.go
  azbfs/zt_url_file_test.go
  ste/xferRetrypolicy.go
Labels: needs-second-review

#792 Safely catch potential errors with the destination blob tier
  ChangeLog.md
  common/fe-ste-models.go
  go.mod
  go.sum
  ste/init.go
  ste/sender-blockBlob.go
  ste/sender-pageBlob.go
  ste/xfer-anyToRemote-file.go
Labels: pr-ready-to-merge

#1058 Allow finer values for job status in jptm
  cmd/jobsClean.go
  cmd/jobsList.go
  cmd/rpc.go
  common/fe-ste-models.go
  ste/JobsAdmin.go
  ste/init.go
  ste/mgr-JobMgr.go
  ste/mgr-JobPartMgr.go
  ste/mgr-JobPartTransferMgr.go
  ste/xfer-anyToRemote-file.go
  ste/xfer-anyToRemote-folder.go
  ste/xfer-remoteToLocal-file.go
  ste/xfer-remoteToLocal-folder.go
Labels: pr-ready-to-merge

#751 Manually unfurl paths to fix long file paths on UNC locations
  cmd/syncIndexer.go
  cmd/zc_enumerator.go
  cmd/zc_traverser_benchmark.go
  cmd/zc_traverser_blob.go
  cmd/zc_traverser_blobfs.go
  cmd/zc_traverser_file.go
  cmd/zc_traverser_local.go
  cmd/zc_traverser_s3.go
  cmd/zt_generic_filter_test.go
Labels: pr-needs-update
