Repository Azure/azure-storage-azcopy, pull requests merged in 2020-06, with the labels that each got.

#1038 update help text to mirror command line options
  cmd/helpMessages.go
Labels: needs-second-review

#1029 Fix file creation error on linux decompressingWriter
  common/writeThoughFile_linux.go
Labels: pr-ready-to-merge

#1016 Stop treating zero-item copy as failure
  ste/init.go
  ste/mgr-JobPartMgr.go
Labels: pr-ready-to-merge

#1007 Benchmark for downloads
  cmd/benchmark.go
  cmd/helpMessages.go
  common/fe-ste-models.go
Labels: pr-ready-to-merge

#1054 Fix GetFileInformation() error on Windows drive root
  common/writeThoughFile_windows.go
Labels: pr-ready-to-merge

#1043 Overwrite content type for static website files
  ste/mgr-JobPartMgr.go
  ste/mgr-JobPartMgr_test.go
Labels: pr-ready-to-merge

#1056 #Issue1032: Removed "\\" from the start of filename when uploaded from root volume in windows
  cmd/copyEnumeratorInit.go
Labels: pr-ready-to-merge

#1002 Add performance information to the logs by wrapping lcm
  cmd/copy.go
  cmd/jobsResume.go
  cmd/root.go
  cmd/rpc.go
  cmd/sync.go
  common/rpc-models.go
  ste/init.go
  ste/joblog_lcm_wrapper.go
Labels: needs-second-review

#1008 Allow rm to delete blob directory stubs with hdi_isfolder
  cmd/copy.go
  cmd/copyEnumeratorInit.go
  cmd/list.go
  cmd/remove.go
  cmd/removeEnumerator.go
  cmd/syncEnumerator.go
  cmd/syncTraverser.go
  cmd/zc_enumerator.go
  cmd/zc_traverser_blob.go
  cmd/zc_traverser_blob_account.go
  cmd/zc_traverser_list.go
  cmd/zt_copy_blob_download_test.go
  cmd/zt_generic_service_traverser_test.go
  cmd/zt_generic_traverser_test.go
  cmd/zt_remove_blob_test.go
  cmd/zt_scenario_helpers_for_test.go
  cmd/zt_test.go
Labels: pr-ready-to-merge

#842 Prototyped new end-to-end testing
  common/output.go
  common/rpc-models.go
  e2etest/config.go
  e2etest/factory.go
  e2etest/runner.go
  e2etest/validator.go
  e2etest/zt_copy_blob_upload_test.go
  e2etest/zt_scenario_helpers.go
  e2etest/zt_scenario_helpers_for_windows.go
  e2etest/zt_test.go
Labels: future release

#1041 Fix/tighten up source properties retrieval for Azure Files
  cmd/zc_traverser_file.go
  ste/sourceInfoProvider-Blob.go
  ste/sourceInfoProvider-File.go
  ste/sourceInfoProvider.go
Labels: pr-ready-to-merge

#1063 Fixed Issue:1028
  cmd/zc_attr_filter_windows.go
Labels: pr-ready-to-merge
