Repository Azure/azure-storage-azcopy, pull requests merged in 2024-09, with the labels that each got.

#2805 Build azcopy go version with 10.23.1
  .github/workflows/build_m1.yml
  .github/workflows/golangci-lint.yml
  azure-pipelines.yml
  go.mod
  perf-test.yaml
Labels: pr-ready-for-review, CVE

#2786 AzCopy sync with --hash-meta-dir causes original files to get hidden
  common/hash_data_adapter_hidden_files.go
  e2etest/scenario_os_helpers.go
  e2etest/scenario_os_helpers_for_linux.go
  e2etest/scenario_os_helpers_for_windows.go
  e2etest/zt_basic_copy_sync_remove_test.go
Labels: pr-ready-for-review

#2801 Added support for Debian 12 package
  packages.csv
  release-pipeline.yml
Labels: pr-ready-to-merge

#2790 Add Scenario for BlobToPipe download and ORP copy operation
  azure-pipelines.yml
  azurePipelineTemplates/run_scenarios.yml
Labels: pr-ready-to-merge

#2814 Regularly clean up E2E resource groups
  e2e-cleanup.ps1
  e2e-cleanup.yml
Labels: pr-ready-to-merge

#2651 New E2E plan file validation
  common/fe-ste-models.go
  e2etest/declarativeTestFiles.go
  e2etest/newe2e_assertions.go
  e2etest/newe2e_generic_wrangling.go
  e2etest/newe2e_object_content.go
  e2etest/newe2e_object_resource_mapping.go
  e2etest/newe2e_resource_definitions.go
  e2etest/newe2e_resource_manager_getter.go
  e2etest/newe2e_resource_managers_blob.go
  e2etest/newe2e_resource_managers_blobfs.go
  e2etest/newe2e_resource_managers_file.go
  e2etest/newe2e_resource_managers_local.go
  e2etest/newe2e_runazcopy_stdout.go
  e2etest/newe2e_sas_generation.go
  e2etest/newe2e_scenario_manager.go
  e2etest/newe2e_scenario_variation_manager.go
  e2etest/newe2e_suite_manager.go
  e2etest/newe2e_task_azcopy_job_validate.go
  e2etest/newe2e_task_resourcemanagement.go
  e2etest/newe2e_task_runazcopy.go
  e2etest/zt_newe2e_basic_functionality_test.go
  e2etest/zt_newe2e_list_test.go
  ste/JobPartPlanFileName.go
  ste/folderCreationTracker.go
  ste/sender-blobFS.go
Labels: pr-ready-to-merge
