Repository Azure/azure-storage-azcopy, pull requests merged in 2024-02, with the labels that each got.

#2562 Changed login deprecation notice
  cmd/login.go
Labels: pr-ready-to-merge

#2554 [RCA Repair Item]Retried deletes should ignore 404 errors
  ste/sender-appendBlob_test.go
  ste/sender-deleteHNSBlob_test.go
  ste/sender_blockBlob_test.go
  ste/sourceInfoProvider_md5_test.go
  ste/testJobPartTransferManager_test.go
  ste/xfer-deleteBlobFS.go
Labels: pr-ready-to-merge

#2568 Fixed a bug where page blob download optimizer would behave incorrectly on highly fragemented blobs if the service times out
  mock_server/closer.go
  mock_server/closer_test.go
  mock_server/doc.go
  mock_server/mock.go
  mock_server/mock_test.go
  ste/pageRangeOptimizer.go
  ste/pageRangeOptimizer_test.go
  ste/sender-pageBlobFromURL.go
  ste/sender_pageBlobFromURL_test.go
Labels: pr-ready-for-review

#2566 New End-to-End testing framework
  .github/workflows/golangci-lint.yml
  azure-pipelines.yml
  cmd/pathUtils.go
  cmd/zc_attr_filter_windows.go
  common/fe-ste-models.go
  e2etest/arm.go
  e2etest/config.go
  e2etest/declarativeHelpers.go
  e2etest/declarativeResourceAdapters.go
  e2etest/declarativeResourceManagers.go
  e2etest/declarativeRunner.go
  e2etest/declarativeScenario.go
  e2etest/declarativeTestFiles.go
  e2etest/managedDisks.go
  e2etest/newe2e_account_registry.go
  e2etest/newe2e_arm_client.go
  e2etest/newe2e_arm_managed_disk.go
  e2etest/newe2e_arm_resource_group.go
  e2etest/newe2e_arm_storage_account.go
  e2etest/newe2e_arm_subscription.go
  e2etest/newe2e_arm_test_hooks.go
  e2etest/newe2e_asserter.go
  e2etest/newe2e_assertions.go
  e2etest/newe2e_config.go
  e2etest/newe2e_error_definition.go
  e2etest/newe2e_generic_wrangling.go
  e2etest/newe2e_multi_step_uploader.go
  e2etest/newe2e_oauth_cache.go
  e2etest/newe2e_object_content.go
  e2etest/newe2e_object_resource_mapping.go
  e2etest/newe2e_resource_definitions.go
  e2etest/newe2e_resource_manager_azstorage.go
  e2etest/newe2e_resource_manager_interface.go
  e2etest/newe2e_resource_manager_mock.go
  e2etest/newe2e_resource_managers_blob.go
  e2etest/newe2e_resource_managers_blobfs.go
  e2etest/newe2e_resource_managers_file.go
  e2etest/newe2e_resource_trie.go
  e2etest/newe2e_sas_generation.go
  e2etest/newe2e_scenario_manager.go
  e2etest/newe2e_scenario_options.go
  e2etest/newe2e_scenario_variation_manager.go
  e2etest/newe2e_suite_manager.go
  e2etest/newe2e_task_azcopy_job_validate.go
  e2etest/newe2e_task_resourcemanagement.go
  e2etest/newe2e_task_runazcopy.go
  e2etest/newe2e_task_runazcopy_parameters.go
  e2etest/newe2e_variations.go
  e2etest/runner.go
  e2etest/zt_newe2e_example_test.go
  e2etest/zt_newe2e_testmain_test.go
  ste/securityInfoPersistenceManager.go
  ste/sender-azureFile.go
Labels: pr-ready-for-review, New E2E testing framework

#2561 Specify very large block size to force put blob instead of stage block/put block list
  cmd/benchmark.go
  cmd/copy.go
  cmd/sync.go
  cmd/syncEnumerator.go
  common/fe-ste-models.go
  common/rpc-models.go
  e2etest/declarativeHelpers.go
  e2etest/runner.go
  e2etest/zt_basic_copy_sync_remove_test.go
  ste/JobPartPlan.go
  ste/JobPartPlanFileName.go
  ste/mgr-JobPartTransferMgr.go
  ste/s2sCopier-URLToBlob.go
  ste/sender-appendBlob.go
  ste/sender-azureFile.go
  ste/sender-blobFS.go
  ste/sender-blockBlob.go
  ste/sender-blockBlobFromLocal.go
  ste/sender-blockBlobFromURL.go
  ste/sender-pageBlob.go
  ste/sender.go
Labels: pr-ready-for-review
