Repository Azure/azure-storage-azcopy, pull requests merged in 2025-08, with the labels that each got.

#3158 Exit LCM refactor
  cmd/copy.go
  cmd/jobsList.go
  cmd/jobsResume.go
  cmd/jobsShow.go
  cmd/pause.go
  cmd/sync.go
  cmd/syncEnumerator.go
  cmd/zt_interceptors_for_test.go
  common/jobLifecycleHandler.go
  common/lifecyleMgr.go
  common/output.go
Labels: pr-ready-for-review, library

#3168 Clean up with LCM
  azcopy/client.go
  cmd/copy.go
  cmd/copyEnumeratorInit.go
  cmd/copyProcess.go
  cmd/jobsResume.go
  cmd/list.go
  cmd/removeProcessor.go
  cmd/root.go
  cmd/setPropertiesProcessor.go
  cmd/sync.go
  cmd/syncEnumerator.go
  cmd/zt_interceptors_for_test.go
  common/jobLifecycleHandler.go
  common/lifecyleMgr.go
  common/logger.go
  jobsAdmin/JobsAdmin.go
Labels: pr-ready-to-merge, library

#3165 Add missing --exclude-path flag to azcopy remove command
  cmd/remove.go
  e2etest/newe2e_task_runazcopy_parameters.go
  e2etest/zt_newe2e_remove_test.go
Labels: pr-ready-for-review
