Repository Azure/azure-storage-azcopy, pull requests merged in 2025-06, with the labels that each got.

#3071 Handling of symlinks
  cmd/zc_traverser_local.go
Labels: XDM

#3090 Copy command code refactor
  cmd/constants.go
  cmd/copy.go
  cmd/copyEnumeratorInit.go
  cmd/copyProcess.go
  cmd/copyUtil.go
  cmd/copyValidation.go
  cmd/remove.go
  cmd/removeEnumerator.go
  cmd/setProperties.go
  cmd/setPropertiesEnumerator.go
  cmd/setPropertiesProcessor.go
  cmd/sync.go
  cmd/zt_copy_s2smigration_test.go
  common/fe-ste-models.go
Labels: pr-ready-to-merge, library

#3062 Initialization code refactor
  cmd/benchmark.go
  cmd/copy.go
  cmd/copyProcess.go
  cmd/copyValidation.go
  cmd/credentialUtil.go
  cmd/jobsResume.go
  cmd/list.go
  cmd/loginStatus.go
  cmd/removeProcessor.go
  cmd/root.go
  cmd/root_unix.go
  cmd/root_windows.go
  cmd/setPropertiesProcessor.go
  cmd/sync.go
  cmd/syncEnumerator.go
  main.go
  ste/xfer.go
Labels: library
