Repository Azure/azure-storage-azcopy, pull requests merged in 2025-07, with the labels that each got.

#3054 Update the AzCopy wiki
  cmd/benchmark.go
  cmd/copy.go
  cmd/helpMessages.go
  cmd/jobsClean.go
  cmd/jobsList.go
  cmd/jobsShow.go
  cmd/list.go
  cmd/login.go
  cmd/make.go
  cmd/remove.go
  cmd/root.go
  cmd/setProperties.go
  cmd/sync.go
Labels: pr-ready-to-merge

#3099 Throw error and fail the job if destination share is not present for SMB and NFS both (S2S Copy)
  cmd/constants.go
  cmd/copyEnumeratorInit.go
  cmd/syncEnumerator.go
  cmd/zt_copy_blob_file_test.go
  e2etest/newe2e_telemetry.go
  e2etest/zt_newe2e_nfs_scenarios_test.go
  e2etest/zt_newe2e_sync_test.go
Labels: nfs-support

#3034 Fixed Mariner arm64 docker issue
  build-1es-pipeline.yaml
  docker/DockerfileMarinerArm64
Labels: pr-ready-to-merge

#3108 Add jobs list to library
  azcopy/client.go
  azcopy/client_test.go
  azcopy/client_unix.go
  azcopy/client_windows.go
  azcopy/jobsList.go
  azcopy/jobsList_test.go
  azcopy/jobsShow.go
  cmd/cancel.go
  cmd/copy.go
  cmd/copyEnumeratorHelper.go
  cmd/copyEnumeratorInit.go
  cmd/credentialUtil.go
  cmd/jobsList.go
  cmd/jobsResume.go
  cmd/jobsShow.go
  cmd/pause.go
  cmd/removeEnumerator.go
  cmd/root.go
  cmd/root_windows.go
  cmd/rpc.go
  cmd/setPropertiesEnumerator.go
  cmd/sync.go
  cmd/syncEnumerator.go
  cmd/zc_processor.go
  cmd/zt_copy_account_account_test.go
  cmd/zt_copy_blob_download_test.go
  cmd/zt_copy_blob_file_test.go
  cmd/zt_copy_blob_upload_test.go
  cmd/zt_copy_file_file_test.go
  cmd/zt_copy_s2smigration_test.go
  cmd/zt_generic_processor_test.go
  cmd/zt_interceptors_for_test.go
  cmd/zt_overwrite_posix_properties_test.go
  cmd/zt_remove_blob_test.go
  cmd/zt_remove_copy_test.go
  cmd/zt_remove_file_test.go
  cmd/zt_set_properties_test.go
  cmd/zt_sync_blob_blob_test.go
  cmd/zt_sync_blob_local_test.go
  cmd/zt_sync_comparator_test.go
  cmd/zt_sync_local_blob_test.go
  cmd/zt_sync_local_blob_windows_test.go
  cmd/zt_user_input_test.go
  common/logger.go
  common/output.go
  common/rpc-models.go
  common/util.go
  e2etest/newe2e_runazcopy_stdout.go
  e2etest/newe2e_task_runazcopy.go
  e2etest/newe2e_task_runazcopy_parameters.go
  e2etest/newe2e_task_validation.go
  e2etest/zt_newe2e_jobs_clean_test.go
  e2etest/zt_newe2e_jobs_list_test.go
  e2etest/zt_newe2e_jobs_show_test.go
  jobsAdmin/JobsAdmin.go
  jobsAdmin/init.go
  jobsAdmin/jobsPlanFolderManagement.go
  ste/concurrency.go
  ste/concurrency_test.go
  ste/mgr-JobMgr.go
Labels: pr-ready-to-merge, library

#3130 NFS Phase 1 changes
  cmd/benchmark.go
  cmd/constants.go
  cmd/copy.go
  cmd/copyEnumeratorInit.go
  cmd/copyProcess.go
  cmd/copyValidation.go
  cmd/flagsValidation.go
  cmd/helpMessages.go
  cmd/jobsResume.go
  cmd/list.go
  cmd/make.go
  cmd/pathUtils.go
  cmd/remove.go
  cmd/removeEnumerator.go
  cmd/setProperties.go
  cmd/setPropertiesEnumerator.go
  cmd/sync.go
  cmd/syncEnumerator.go
  cmd/syncProcessor.go
  cmd/validators.go
  cmd/zc_enumerator.go
  cmd/zc_traverser_file.go
  cmd/zc_traverser_local.go
  cmd/zt_copy_blob_file_test.go
  common/fe-ste-models.go
  common/genericResourceURLParts.go
  common/rpc-models.go
  common/util.go
  e2etest/declarativeHelpers.go
  e2etest/declarativeRunner.go
  e2etest/declarativeScenario.go
  e2etest/newe2e_resource_manager_azstorage.go
  e2etest/newe2e_resource_manager_getter.go
  e2etest/newe2e_resource_manager_mock.go
  e2etest/newe2e_resource_managers_file.go
  e2etest/newe2e_task_validation.go
  e2etest/newe2e_telemetry.go
  e2etest/stress_generators/acct_rm.go
  e2etest/validator.go
  e2etest/zt_newe2e_nfs_scenarios_test.go
  e2etest/zt_newe2e_sync_test.go
  jobsAdmin/init.go
  ste/JobPartPlan.go
  ste/JobPartPlanFileName.go
  ste/downloader-azureFiles.go
  ste/mgr-JobPartTransferMgr.go
  ste/sender-azureFile.go
  ste/xfer.go
Labels: pr-ready-to-merge, nfs-support

#3134 Changing azcopy binary name in pipeline to resolve failure
  build-1es-pipeline.yaml
Labels: pr-ready-for-review
