Repository Azure/azure-storage-azcopy, pull requests merged in 2025-09, with the labels that each got.

#3087 Add support for transfer data Azure Files NFS <-> Azure Files SMB
  cmd/copy.go
  cmd/copyEnumeratorHelper.go
  cmd/copyEnumeratorInit.go
  cmd/copyProcess.go
  cmd/copyValidation.go
  cmd/copy_sync_test.go
  cmd/flagsValidation.go
  cmd/sync.go
  cmd/syncEnumerator.go
  cmd/validators.go
  cmd/zc_enumerator.go
  cmd/zc_processor.go
  cmd/zc_traverser_benchmark.go
  cmd/zc_traverser_blob.go
  cmd/zc_traverser_blob_account.go
  cmd/zc_traverser_blob_versions.go
  cmd/zc_traverser_file.go
  cmd/zc_traverser_file_account.go
  cmd/zc_traverser_gcp.go
  cmd/zc_traverser_list.go
  cmd/zc_traverser_local.go
  cmd/zc_traverser_local_other.go
  cmd/zc_traverser_s3.go
  cmd/zt_generic_traverser_test.go
  common/fe-ste-models.go
  common/rpc-models.go
  common/util.go
  e2etest/newe2e_task_runazcopy_parameters.go
  e2etest/zt_newe2e_nfs_scenarios_test.go
  jobsAdmin/init.go
  ste/downloader-azureFiles.go
  ste/jobStatusManager.go
  ste/sender-azureFile.go
Labels: pr-ready-for-review, nfs-support

#3202 LCM refactor
  azcopy/credentialUtil.go
  azcopy/jobsResume.go
  azcopy/pathUtils.go
  azcopy/zt_credentialUtil_test.go
  cmd/cancel.go
  cmd/copy.go
  cmd/jobsResume.go
  cmd/lifecycleMgr.go
  cmd/pause.go
  cmd/removeProcessor.go
  cmd/root.go
  cmd/setPropertiesProcessor.go
  cmd/sync.go
  cmd/syncEnumerator.go
  cmd/zc_traverser_blob.go
  cmd/zc_traverser_blob_versions.go
  cmd/zt_interceptors_for_test.go
  common/credentialFactory.go
  common/fe-ste-models.go
  common/jobLifecycleHandler.go
  common/lifecyleMgr.go
  common/messages.go
  common/output.go
  common/rpc-models.go
  common/zt_ProxyLookupCache_test.go
  e2etest/declarativeResourceManagers.go
  e2etest/declarativeScenario.go
  e2etest/declarativeWithPropertyProviders.go
  e2etest/newe2e_resource_managers_blob.go
  jobsAdmin/JobsAdmin.go
  jobsAdmin/init.go
  main.go
  ste/mgr-JobMgr.go
  ste/mgr-JobPartMgr.go
  ste/mgr-JobPartTransferMgr.go
  ste/sender_blockBlob_test.go
  ste/testJobPartTransferManager_test.go
  ste/xfer-deleteBlob.go
  ste/xfer-deleteBlobFS.go
  ste/xfer-deleteFile.go
  ste/xfer-setProperties.go
Labels: library

#3201 Symlink support for Local to Azure Files NFS
  cmd/copy.go
  cmd/copyEnumeratorHelper.go
  cmd/copyEnumeratorInit.go
  cmd/copyValidation.go
  cmd/flagsValidation.go
  cmd/sync.go
  cmd/syncEnumerator.go
  cmd/syncProcessor.go
  cmd/zc_processor.go
  cmd/zc_traverser_file.go
  cmd/zc_traverser_local.go
  common/rpc-models.go
  common/writeThoughFile_linux.go
  e2etest/newe2e_resource_managers_file.go
  e2etest/newe2e_task_runazcopy_parameters.go
  e2etest/newe2e_task_validation.go
  e2etest/zt_newe2e_nfs_scenarios_test.go
  go.mod
  go.sum
  jobsAdmin/init.go
  ste/JobPartPlan.go
  ste/JobPartPlanFileName.go
  ste/jobStatusManager.go
  ste/sender-azureFile.go
  ste/sender-azureFileFromLocal.go
  ste/sourceInfoProvider-Local_linux.go
Labels: pr-ready-to-merge

#3191 Backward compatibility with older az accounts with AsSecureString
  common/azure_ps_context_credential.go
Labels: pr-ready-for-review

#3203 Added support for jobs resume progress tracking in library
  azcopy/jobLifecycleManager.go
  azcopy/jobsResume.go
  azcopy/jobsShow.go
  azcopy/pathUtils.go
  cmd/constants.go
  cmd/copy.go
  cmd/jobsResume.go
  cmd/jobsShow.go
  cmd/sync.go
  common/constants.go
  common/jobLifecycleHandler.go
  common/lifecyleMgr.go
  common/output.go
Labels: library
